from typing import Callable, Coroutine

from websockets.sync.server import WebSocketServer

from socketd.transport.server.ServerConfig import ServerConfig
from socketd.transport.core import Processor
from socketd.transport.core.Listener import Listener


class Server:
    def config(self, consumer: Callable[[ServerConfig], ServerConfig]) -> 'Server': ...

    def process(self, processor: Processor) -> 'Server': ...

    def listen(self, listener: Listener) -> 'Server': ...

    def start(self) -> WebSocketServer | Coroutine: ...

    def stop(self) -> Coroutine: ...

    def get_assistant(self): ...

    def get_config(self): ...